//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GI_Inc.Properties.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public bool active { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string cityId { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public string countryId { get; set; }
        public string country { get; set; }
        public System.DateTime createDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public string lastUpdateBy { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
