//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GI_Inc.DataSources
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public int agentId { get; set; }
        public string agentName { get; set; }
        public string agentDepartment { get; set; }
        public string agentTimeZone { get; set; }
        public string agentCountry { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<int> agentShift { get; set; }
        public string workDay1 { get; set; }
        public string workDay2 { get; set; }
        public string workDay3 { get; set; }
        public string workDay4 { get; set; }
        public string workDay5 { get; set; }
        public sbyte active { get; set; }
        public System.DateTime createDate { get; set; }
        public string createdBy { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public string lastUpdateBy { get; set; }
    }
}
